app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: PT120S
    force-check-delay: PT10S



spring:
  application:
    name: scrapper
  jooq:
    sql-dialect: postgres
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SCRAPPER_URL}
    username: ${SCRAPPER_USERNAME}
    password: ${SCRAPPER_PASSWORD}


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

client:
  github-url: unset
  stack-overflow-url: unset

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
