app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: PT120S
    force-check-delay: PT10S

spring:
  application:
    name: scrapper
  jooq:
    sql-dialect: postgres
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SCRAPPER_URL}
    username: ${SCRAPPER_USERNAME}
    password: ${SCRAPPER_PASSWORD}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

client:
  github:
    url: unset
    interval: PT60S
    back-off: linear
    codes: bad_gateway, internal_server_error, service_unavailable, forbidden
    max-attempts: 10
  stack-overflow:
    url: unset
    interval: PT60S
    back-off: exponential
    codes: bad_gateway, internal_server_error, service_unavailable, forbidden
    max-attempts: 10
  bot:
    url: unset
    interval: PT60S
    back-off: constant
    codes:
    max-attempts: 10

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
