app:
  telegram-token: ${BACKEND_JAVA_BOT_TOKEN}


spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true

client:
  scrapper:
    url: unset
    interval: PT60S
    back-off: linear
    codes: bad_gateway, internal_server_error, service_unavailable, forbidden
    max-attempts: 10
