/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables.pojos;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChatsAndLinks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long chatId;
    private Long linkId;
    private String alias;

    public ChatsAndLinks() {
    }

    public ChatsAndLinks(ChatsAndLinks value) {
        this.chatId = value.chatId;
        this.linkId = value.linkId;
        this.alias = value.alias;
    }

    @ConstructorProperties({"chatId", "linkId", "alias"})
    public ChatsAndLinks(
        @NotNull Long chatId,
        @NotNull Long linkId,
        @NotNull String alias
    ) {
        this.chatId = chatId;
        this.linkId = linkId;
        this.alias = alias;
    }

    /**
     * Getter for <code>CHATS_AND_LINKS.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>CHATS_AND_LINKS.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>CHATS_AND_LINKS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>CHATS_AND_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>CHATS_AND_LINKS.ALIAS</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getAlias() {
        return this.alias;
    }

    /**
     * Setter for <code>CHATS_AND_LINKS.ALIAS</code>.
     */
    public void setAlias(@NotNull String alias) {
        this.alias = alias;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ChatsAndLinks other = (ChatsAndLinks) obj;
        if (this.chatId == null) {
            if (other.chatId != null) {
                return false;
            }
        } else if (!this.chatId.equals(other.chatId)) {
            return false;
        }
        if (this.linkId == null) {
            if (other.linkId != null) {
                return false;
            }
        } else if (!this.linkId.equals(other.linkId)) {
            return false;
        }
        if (this.alias == null) {
            if (other.alias != null) {
                return false;
            }
        } else if (!this.alias.equals(other.alias)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.alias == null) ? 0 : this.alias.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatsAndLinks (");

        sb.append(chatId);
        sb.append(", ").append(linkId);
        sb.append(", ").append(alias);

        sb.append(")");
        return sb.toString();
    }
}
