/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables;

import edu.java.scrapper.domain.jooq.DefaultSchema;
import edu.java.scrapper.domain.jooq.Keys;
import edu.java.scrapper.domain.jooq.tables.Chats.ChatsPath;
import edu.java.scrapper.domain.jooq.tables.Links.LinksPath;
import edu.java.scrapper.domain.jooq.tables.records.ChatsAndLinksRecord;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChatsAndLinks extends TableImpl<ChatsAndLinksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CHATS_AND_LINKS</code>
     */
    public static final ChatsAndLinks CHATS_AND_LINKS = new ChatsAndLinks();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<ChatsAndLinksRecord> getRecordType() {
        return ChatsAndLinksRecord.class;
    }

    /**
     * The column <code>CHATS_AND_LINKS.CHAT_ID</code>.
     */
    public final TableField<ChatsAndLinksRecord, Long> CHAT_ID =
        createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CHATS_AND_LINKS.LINK_ID</code>.
     */
    public final TableField<ChatsAndLinksRecord, Long> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CHATS_AND_LINKS.ALIAS</code>.
     */
    public final TableField<ChatsAndLinksRecord, String> ALIAS =
        createField(DSL.name("ALIAS"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    private ChatsAndLinks(Name alias, Table<ChatsAndLinksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChatsAndLinks(Name alias, Table<ChatsAndLinksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>CHATS_AND_LINKS</code> table reference
     */
    public ChatsAndLinks(String alias) {
        this(DSL.name(alias), CHATS_AND_LINKS);
    }

    /**
     * Create an aliased <code>CHATS_AND_LINKS</code> table reference
     */
    public ChatsAndLinks(Name alias) {
        this(alias, CHATS_AND_LINKS);
    }

    /**
     * Create a <code>CHATS_AND_LINKS</code> table reference
     */
    public ChatsAndLinks() {
        this(DSL.name("CHATS_AND_LINKS"), null);
    }

    public <O extends Record> ChatsAndLinks(
        Table<O> path,
        ForeignKey<O, ChatsAndLinksRecord> childPath,
        InverseForeignKey<O, ChatsAndLinksRecord> parentPath
    ) {
        super(path, childPath, parentPath, CHATS_AND_LINKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChatsAndLinksPath extends ChatsAndLinks implements Path<ChatsAndLinksRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> ChatsAndLinksPath(
            Table<O> path,
            ForeignKey<O, ChatsAndLinksRecord> childPath,
            InverseForeignKey<O, ChatsAndLinksRecord> parentPath
        ) {
            super(path, childPath, parentPath);
        }

        private ChatsAndLinksPath(Name alias, Table<ChatsAndLinksRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChatsAndLinksPath as(String alias) {
            return new ChatsAndLinksPath(DSL.name(alias), this);
        }

        @Override
        public ChatsAndLinksPath as(Name alias) {
            return new ChatsAndLinksPath(alias, this);
        }

        @Override
        public ChatsAndLinksPath as(Table<?> alias) {
            return new ChatsAndLinksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<ChatsAndLinksRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D;
    }

    @Override
    @NotNull
    public List<UniqueKey<ChatsAndLinksRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CHAT_ID_ALIAS_UNIQUE);
    }

    @Override
    @NotNull
    public List<ForeignKey<ChatsAndLinksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_D5, Keys.CONSTRAINT_D54);
    }

    private transient ChatsPath _chats;

    /**
     * Get the implicit join path to the <code>PUBLIC.CHATS</code> table.
     */
    public ChatsPath chats() {
        if (_chats == null) {
            _chats = new ChatsPath(this, Keys.CONSTRAINT_D5, null);
        }

        return _chats;
    }

    private transient LinksPath _links;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public LinksPath links() {
        if (_links == null) {
            _links = new LinksPath(this, Keys.CONSTRAINT_D54, null);
        }

        return _links;
    }

    @Override
    @NotNull
    public ChatsAndLinks as(String alias) {
        return new ChatsAndLinks(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public ChatsAndLinks as(Name alias) {
        return new ChatsAndLinks(alias, this);
    }

    @Override
    @NotNull
    public ChatsAndLinks as(Table<?> alias) {
        return new ChatsAndLinks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatsAndLinks rename(String name) {
        return new ChatsAndLinks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatsAndLinks rename(Name name) {
        return new ChatsAndLinks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatsAndLinks rename(Table<?> name) {
        return new ChatsAndLinks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatsAndLinks where(Condition condition) {
        return new ChatsAndLinks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatsAndLinks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatsAndLinks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatsAndLinks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public ChatsAndLinks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public ChatsAndLinks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public ChatsAndLinks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public ChatsAndLinks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatsAndLinks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public ChatsAndLinks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
